workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d{1,}\.\d{1,}\.\d{1,}$/
      when: always

stages:
  - build
  - deploy

variables:
  S3_BUCKET_NAME: "my-demo-build"
  JAR_PATH: ./demo-$CI_COMMIT_TAG.jar

build:
  stage: build
  image: openjdk:8-jdk-alpine
  before_script:
    - chmod +x mvnw
  script:
    - ./mvnw clean package
    - cp ./target/demo-*.jar $JAR_PATH
  artifacts:
    paths:
      - $JAR_PATH
    expire_in: 1 day

push-to-s3:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws s3 cp $JAR_PATH s3://$S3_BUCKET_NAME/ --metadata x-amz-meta-commit-sha=$CI_COMMIT_SHORT_SHA
