workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d{1,}\.\d{1,}\.\d{1,}$/
      when: always

stages:
  - build
  - deploy

variables:
  S3_BUCKET_NAME: "my-demo-build"
  JAR_PATH: ./demo-$CI_COMMIT_TAG.jar
  TAR_NAME: demo-$CI_COMMIT_TAG.tar
  CODEDEPLOY_APPSPEC_PATH: ./appspec.yml
  CODEDEPLOY_SCRIPTS_PATH: ./scripts

build:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - chmod +x mvnw
    - ./mvnw clean package
    - cp ./target/demo-*.jar $JAR_PATH
    - tar -cvf $TAR_NAME $JAR_PATH $CODEDEPLOY_APPSPEC_PATH $CODEDEPLOY_SCRIPTS_PATH
  artifacts:
    paths:
      - ./$TAR_NAME
    expire_in: 1 day

push-to-s3:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp ./$TAR_NAME s3://$S3_BUCKET_NAME/ --metadata x-amz-meta-commit-sha=$CI_COMMIT_SHORT_SHA
